version: '2'
services:
  chat-server:
    container_name: chat-server
    image: chat-server
    build: .
    ports:
      - 1337:1337

  rethink:
    container_name: rethink
    image: rethinkdb

  redis:
    container_name: redis 
    image: redis
