module.exports = {
  CHAT_URL: 'localhost:1337',
  CHAT_END_WS: 'pull',
  CHAT_END_ADD: 'add',
  CHAT_END_DEL: 'del',
  CHAT_END_GET: 'get',
  CHAT_END_REG: 'reg',
  CHAT_END_SHOW: 'show',
  CHAT_END_WAIT: 'wait',
  CHAT_KEY_PUB: 'pub',
  CHAT_KEY_SUB: 'sub',
  CHAT_KEY_UNSUB: 'unsub',
  CHAT_KEY_MSG: 'msg',
  CHAT_KEY_REFRESH: 'refresh',
  CHAT_KEY_NOTIFY: 'notify',
}
